#!/usr/bin/env bash


# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

echo "We will install the label printing shizzle..."
install -v -C --owner=root --mode=uga+rwx k2h /usr/local/bin/k2h

