#!/usr/bin/env bash

#python gpgkeypipe < test.json

NAME="Betta"
EMAIL="email@invalid.tld"


echo "Copying books..."
if [ -f "/usr/local/share/key2myheart/k2h-bookshelf.tar.gz" ] 
then
	tar xf /usr/local/share/key2myheart/k2h-bookshelf.tar.gz -C /media/$USER/USB\ DISK
fi

date
#echo "gpgkeypipe k2myheart --name=\"$1\"" --email=\"$2\" --out=/media/$USER/USB\ DISK"
#gpgkeypipe k2myheart --name="$1" --email="$2" --out="/media/$USER/USB\ DISK"&

echo "Generating cryptographic keys..."
gpgkeypipe k2myheart --name="$NAME" --email="$EMAIL" --out="/media/$USER/USB DISK"

date

echo "Generating PDF..."
k2h generate --name="$NAME" --email="$EMAIL" < /tmp/revcert.asc

echo "Printing identity label..."
k2h print --orientation=landscape --pdf=/tmp/label.pdf

