#!/bin/sh

# make sure this script is run by root only
if [ "$(id -u)" != "0" ]; then
	fatal "This script must be run as root"
	exit 1
fi

PACKAGES="coreutils gnupg2"
# install apt get packages
for dep in $PACKAGES
do
	echo "\033[47;34m>>> installing package $dep\033[0m"
	apt-get install -q -y $dep || fatal "unable to install $dep"
done


PYLIBS="gnupg qrcode docopt pexpect"
# install python dependency
for dep in $PYLIBS
do
	echo "\033[47;34m>>> installing python library $dep\033[0m"
	pip install $dep || fatal "unable to install $dep"
done

