#!/usr/bin/env bash

## Control script for biotrpyd daemon
## (cc) 2014 Luis Rodil-Fernandez
##
## this script uses the command line tool oscsend
## which is included in liblo http://liblo.sourceforge.net/
## download latest version compile from source and install
## library will install in /usr/local/lib
## so we have to rebuild the library cache 
## with: sudo ldconfig -v
##
env > /tmp/env.out

echo $ACTION > /tmp/action.out
echo $DEVNAME >> /tmp/action.out

if [ $ACTION = "add" ] 
then
    echo $DEVNAME > /tmp/backuptousbdrive.out
	# send osc message to notify of usb drive presence
	oscsend osc.udp://localhost:12345 /k2h/thumbdrive s add
else
    echo "unknown"  > /tmp/backuptousbdrive.out
fi

