#!/usr/bin/env bash

## Control script for biotrpyd daemon
## (cc) 2014 Luis Rodil-Fernandez

env > /tmp/env.out

echo $ACTION > /tmp/action.out
echo $DEVNAME >> /tmp/action.out

if [ "$ACTION" = "add" ] 
then
    echo $DEVNAME > /tmp/backuptousbdrive.out
else
    echo "unknown"  > /tmp/backuptousbdrive.out
fi
