#!/usr/bin/env bash


# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

echo "We will install the USB auto shizzle moving parts..."
install -v -C --owner=root --mode=u+rw 90-k2h-usb.rules /etc/udev/rules.d/90-k2h-usb.rules
install -v -C --owner=root --mode=u+rwx ctlk2husb /usr/local/bin/ctlk2husb
install -v -C --owner=root --mode=uga+rwx k2hcopybookshelf /usr/local/bin/k2hcopybookshelf
sudo udevadm control --reload-rules

